// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIiafel-JFM4wEeQaHG-3bAB_fJFtddR4',
    appId: '1:196013058870:web:af1c436ce3ae457e476197',
    messagingSenderId: '196013058870',
    projectId: 'chatter-matters',
    authDomain: 'chatter-matters.firebaseapp.com',
    storageBucket: 'chatter-matters.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSWcW3b53RVuugc5bloOFS-X4NqTB8i8',
    appId: '1:196013058870:android:9c8dfc7eb17b1cab476197',
    messagingSenderId: '196013058870',
    projectId: 'chatter-matters',
    storageBucket: 'chatter-matters.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzK4AWYwoIZx7DuAP2QNBQU_T5_PdgaRI',
    appId: '1:196013058870:ios:c9271c51558d5413476197',
    messagingSenderId: '196013058870',
    projectId: 'chatter-matters',
    storageBucket: 'chatter-matters.firebasestorage.app',
    iosClientId: '196013058870-1ctnjl2j7t20sp4flifsgfe7ga3jqo1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterMatterApp',
  );
}
